-- Roles lookup table (admin / teacher / student)
CREATE TABLE roles (
  role_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(20) NOT NULL,
  description VARCHAR2(255),
  CONSTRAINT uq_roles_name UNIQUE (name),
  CONSTRAINT ck_roles_name CHECK (name IN ('admin', 'teacher', 'student'))
)
/
