-- Application users
CREATE TABLE users (
  user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id       NUMBER NOT NULL,
  full_name     VARCHAR2(120) NOT NULL,
  email         VARCHAR2(180) NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  is_active     NUMBER(1) DEFAULT 1 NOT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT ck_users_active CHECK (is_active IN (0, 1)),
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(role_id)
)
/
CREATE INDEX ix_users_role_id ON users(role_id)
/
