-- Algorithm categories
CREATE TABLE categories (
  category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR2(60) NOT NULL,
  name          VARCHAR2(80) NOT NULL,
  description   VARCHAR2(400),
  display_order NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT uq_categories_slug UNIQUE (slug)
)
/
