-- Algorithms (the catalog heart). `slug` joins to the client-side step-generator.
CREATE TABLE algorithms (
  algorithm_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id      NUMBER NOT NULL,
  slug             VARCHAR2(80) NOT NULL,
  name             VARCHAR2(120) NOT NULL,
  summary          VARCHAR2(400),
  description      CLOB,
  visualizer_type  VARCHAR2(20) NOT NULL,
  difficulty       VARCHAR2(10),
  space_complexity VARCHAR2(40),
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_algorithms_slug UNIQUE (slug),
  CONSTRAINT ck_algorithms_viz CHECK (visualizer_type IN ('array', 'grid', 'graph', 'matrix', 'string', 'math')),
  CONSTRAINT ck_algorithms_diff CHECK (difficulty IN ('easy', 'medium', 'hard')),
  CONSTRAINT fk_algorithms_category FOREIGN KEY (category_id) REFERENCES categories(category_id)
)
/
CREATE INDEX ix_algorithms_category_id ON algorithms(category_id)
/
