-- Time complexity per case (best / average / worst) — one row per case (3NF)
CREATE TABLE time_complexities (
  complexity_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  algorithm_id  NUMBER NOT NULL,
  case_type     VARCHAR2(10) NOT NULL,
  big_o         VARCHAR2(40) NOT NULL,
  CONSTRAINT uq_timecplx_algo_case UNIQUE (algorithm_id, case_type),
  CONSTRAINT ck_timecplx_case CHECK (case_type IN ('best', 'average', 'worst')),
  CONSTRAINT fk_timecplx_algo FOREIGN KEY (algorithm_id) REFERENCES algorithms(algorithm_id) ON DELETE CASCADE
)
/
CREATE INDEX ix_timecplx_algo ON time_complexities(algorithm_id)
/
