-- Source code per algorithm, one row per language
CREATE TABLE code_snippets (
  snippet_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  algorithm_id NUMBER NOT NULL,
  language     VARCHAR2(20) NOT NULL,
  code         CLOB NOT NULL,
  CONSTRAINT uq_snippet_algo_lang UNIQUE (algorithm_id, language),
  CONSTRAINT ck_snippet_lang CHECK (language IN ('javascript', 'python', 'cpp', 'java', 'pseudocode')),
  CONSTRAINT fk_snippet_algo FOREIGN KEY (algorithm_id) REFERENCES algorithms(algorithm_id) ON DELETE CASCADE
)
/
CREATE INDEX ix_snippet_algo ON code_snippets(algorithm_id)
/
