-- Bookmarks: users M:N algorithms
CREATE TABLE bookmarks (
  bookmark_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      NUMBER NOT NULL,
  algorithm_id NUMBER NOT NULL,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_bookmark_user_algo UNIQUE (user_id, algorithm_id),
  CONSTRAINT fk_bookmark_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_bookmark_algo FOREIGN KEY (algorithm_id) REFERENCES algorithms(algorithm_id) ON DELETE CASCADE
)
/
CREATE INDEX ix_bookmark_user ON bookmarks(user_id)
/
