-- Progress: users M:N algorithms, with learning status
CREATE TABLE progress (
  progress_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        NUMBER NOT NULL,
  algorithm_id   NUMBER NOT NULL,
  status         VARCHAR2(15) NOT NULL,
  last_viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_progress_user_algo UNIQUE (user_id, algorithm_id),
  CONSTRAINT ck_progress_status CHECK (status IN ('not_started', 'in_progress', 'completed')),
  CONSTRAINT fk_progress_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_progress_algo FOREIGN KEY (algorithm_id) REFERENCES algorithms(algorithm_id) ON DELETE CASCADE
)
/
CREATE INDEX ix_progress_user ON progress(user_id)
/
