-- In-depth explanation sections per algorithm (one row per section).
CREATE TABLE algorithm_explanations (
  explanation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  algorithm_id   NUMBER NOT NULL,
  heading        VARCHAR2(120) NOT NULL,
  body           CLOB NOT NULL,
  display_order  NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT fk_expl_algo FOREIGN KEY (algorithm_id) REFERENCES algorithms(algorithm_id) ON DELETE CASCADE
)
/
CREATE INDEX ix_expl_algo ON algorithm_explanations(algorithm_id)
/
